/**
 * En este desaf√≠o vas a conectarte a una API que no existe, por ende debes capturar el error haciendo uso de try/catch y lanzar un error con el mensaje API No Found.
 * La soluci√≥n deber√≠a tener un input y output como los siguientes:
 *
 * Input: await runCode();
 *
 * Output: Error: API No Found
 */

export async function runCode() {
  // Tu c√≥digo aqu√≠ üëà
  const url = 'https://domain-api-com'

  const response = await fetch(url)
  try {
    console.log(response.json())
  } catch (error) {
    console.error('Error: ', error)
  }
}
